on: [ push ]

jobs:
  self_test:
    runs-on: ubuntu-latest
    name: Running git secrets --scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: git secrets
        uses: ./